services:
  - type: web
    name: dixieClone
    runtime: docker 
    plan: starter
    autoDeploy: true
    dockerfilePath: servers/dixie/Dockerfile    
    buildFilter:
      paths:
        - servers/dixie/*.json
        - servers/dixie/**/*.ts
        - servers/dixie/Dockerfile
    envVars:
      - fromGroup: servers/dixieClone
      - key: DATABASE_URL
        fromDatabase:
          name: dixieCloneDB
          property: connectionString
    domains:
      - v1.api.clone.tekfinance.fun
  - type: web
    name: kitkatClone
    runtime: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: web/kitkat/Dockerfile    
    buildFilter:
      paths:
        - web/kitkat/*.json
        - web/kitkat/**/*.ts
        - web/kitkat/Dockerfile
    envVars:
      - fromGroup: web/kitkatClone
      - key: API_BASE_URL
        fromService: 
          type: web
          name: dixieClone
          envVarKey: RENDER_EXTERNAL_URL
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService: 
          type: web
          name: dixieClone
          envVarKey: RENDER_EXTERNAL_URL
    domains:
      - bot.clone.tekfinance.fun
databases:
  - name: dixieCloneDB
    user: admin
    